# Generated by Django 4.2.14 on 2024-08-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField()),
                ('duracion', models.IntegerField(default=600)),
                ('tiempo_agregado_por_jugada', models.IntegerField(default=3)),
                ('color_usuario_solicitante', models.CharField(max_length=50)),
                ('color_usuario_destinatario', models.CharField(max_length=50)),
                ('usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_recibidas', to='Usuarios.perfilusuario')),
                ('usuario_ganador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_ganadas', to='Usuarios.perfilusuario')),
                ('usuario_perdedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_perdidas', to='Usuarios.perfilusuario')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_solicitadas', to='Usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptada', models.BooleanField()),
                ('esAmigo', models.BooleanField(default=False)),
                ('usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_recibidas', to='Usuarios.perfilusuario')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_solicitadas', to='Usuarios.perfilusuario')),
            ],
        ),
    ]
